<?xml version="1.0"?>
<robot name="fortnight"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Defines the kobuki component tag. -->
  <xacro:include filename="$(find kobuki_description)/urdf/kobuki.urdf.xacro" />
  <xacro:include filename="$(find sick_tim)/urdf/sick_tim.urdf.xacro" />


  <kobuki/>

  <joint name="laser_base_joint" type="fixed">
	  <!-- some parts are running on indigo, from jade , tehre is constant pi, use it instead on newer robots -->
	  <!-- there are also no trigonometric functions in old versions, so we will compute it outside -->
	  <xacro:property name="PI" value="3.14159265358979" />
	  <xacro:property name="radius" value=".206" />
	  <xacro:property name="angle" value="${-PI/4 + 0.15}" />
	  <xacro:property name="x" value="${ .80483545108964388920 * radius}" /> <!-- cos(angle) * distance -->
	  <xacro:property name="y" value="${-.59349801740977150377 * radius}" /> <!-- sin(angle) * distance -->
	  <origin rpy="${PI} 0 ${angle}" xyz="${x} ${y} 0.0908"/>
    	<parent link="base_link"/>
    	<child link="laser_mount_link"/>
  	</joint>
  	<xacro:sick_tim310 name="laser" ros_topic="scan" />
</robot>
